command = "/usr/sbin/nginx -g 'daemon off;'"
start-delay = "0s"
stdout = "/logs/nginx-stdout.log"
stderr = "/logs/nginx-stderr.log"
working-directory = "/etc/nginx"

[restart]
strategy = "always"
backoff = "5s"
attempts = 0

[healthiness]
http-endpoint = "http://localhost:80/health"

[termination]
signal = "TERM"
wait = "10s"
